# This file provides a list of supported TradingView market codes and human-friendly names.
# These can be used for country/region selection in the Streamlit UI.

MARKETS = [
    ("United States", "america"),
    ("Canada", "canada"),
    ("Brazil", "brazil"),
    ("Mexico", "mexico"),
    ("United Kingdom", "uk"),
    ("Germany", "germany"),
    ("France", "france"),
    ("Italy", "italy"),
    ("Spain", "spain"),
    ("Netherlands", "netherlands"),
    ("Switzerland", "switzerland"),
    ("Sweden", "sweden"),
    ("Norway", "norway"),
    ("Finland", "finland"),
    ("Denmark", "denmark"),
    ("Belgium", "belgium"),
    ("Austria", "austria"),
    ("Poland", "poland"),
    ("Portugal", "portugal"),
    ("Greece", "greece"),
    ("Hungary", "hungary"),
    ("Czech Republic", "czech"),
    ("Russia", "russia"),
    ("Turkey", "turkey"),
    ("Israel", "israel"),
    ("Japan", "japan"),
    ("China", "china"),
    ("Hong Kong", "hongkong"),
    ("India", "india"),
    ("Singapore", "singapore"),
    ("South Korea", "korea"),
    ("Taiwan", "taiwan"),
    ("Australia", "australia"),
    ("New Zealand", "newzealand"),
    ("South Africa", "southafrica"),
    ("Egypt", "egypt"),
    ("Nigeria", "nigeria"),
    # Asset classes (not countries)
    ("Crypto", "crypto"),
    ("Forex", "forex"),
    ("Coin", "coin"),
    ("CFD", "cfd"),
    ("Futures", "futures"),
    ("Bonds", "bonds"),
    ("Economy", "economy"),
    ("Options", "options"),
]
